In [96]:
from collections import Counter
from sklearn.datasets import make_classification
from imblearn.over_sampling import SMOTE, ADASYN
from plotly.subplots import make_subplots
import plotly.graph_objects as go
X, y = make_classification(n_classes=3, weights=[0.03, 0.07,0.9],n_features=2,
    n_redundant=0, n_clusters_per_class=1, n_samples=1000, random_state=0)
print('Original dataset shape %s' % Counter(y)) 

Original dataset shape Counter({2: 893, 1: 74, 0: 33})


In [97]:
sm0 = SMOTE(k_neighbors=3)
X0, y0 = sm0.fit_resample(X, y)

sm1 = SMOTE(k_neighbors=6)
X1, y1 = sm1.fit_resample(X, y)

sm2 = SMOTE(k_neighbors=9)
X2, y2 = sm2.fit_resample(X, y)

print('Original dataset shape %s' % Counter(y1)) 

Original dataset shape Counter({2: 893, 1: 893, 0: 893})


In [83]:
def SetColor(x):
    if x==0:
        return 'red'
    elif x==1:
        return 'green'
    else :
        return 'blue'

In [124]:
fig = make_subplots(
    rows=2, cols=2,
    column_widths=[2, 2], row_heights=[2, 2],
    subplot_titles=("Original", "SMOTE with k=3", "SMOTE with k=6", "Smote with k=9"))

fig.add_trace(
    go.Scatter(x=X[:,0], y=X[:,1],
        mode='markers', marker=dict(color=list(map(SetColor, y))),
        showlegend=False),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(x=X0[:,0], y=X0[:,1],
              mode='markers', marker=dict(color=list(map(SetColor, y0))),
              showlegend=False),
    row=1, col=2
)

fig.add_trace(
    go.Scatter(x=X1[:,0], y=X1[:,1],
              mode='markers', marker=dict(color=list(map(SetColor, y1))),
              showlegend=False),
    row=2, col=1
)

fig.add_trace(
    go.Scatter(x=X2[:,0], y=X2[:,1],
              mode='markers', marker=dict(color=list(map(SetColor, y2))),
              showlegend=False),
    row=2, col=2
)

fig.update_layout(title_text='SMOTE with K_neighbors')

fig.show()

In [121]:
ad0 = ADASYN(n_neighbors=3)
X3, y3 = ad0.fit_resample(X, y)

ad1 = ADASYN(n_neighbors=6)
X4, y4 = ad1.fit_resample(X, y)

ad2 = ADASYN(n_neighbors=9)
X5, y5 = ad2.fit_resample(X, y)

print('Original dataset shape %s' % Counter(y1)) 

Original dataset shape Counter({2: 893, 1: 893, 0: 893})


In [123]:
fig = make_subplots(
    rows=2, cols=2,
    column_widths=[2, 2], row_heights=[2, 2],
    subplot_titles=("Original", "ADASYN with k=3", "ADASYN with k=6", "ADASYN with k=9"))

fig.add_trace(
    go.Scatter(x=X[:,0], y=X[:,1],
        mode='markers', marker=dict(color=list(map(SetColor, y))),
        showlegend=False),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(x=X3[:,0], y=X3[:,1],
              mode='markers', marker=dict(color=list(map(SetColor, y3))),
              showlegend=False),
    row=1, col=2
)

fig.add_trace(
    go.Scatter(x=X4[:,0], y=X4[:,1],
              mode='markers', marker=dict(color=list(map(SetColor, y4))),
              showlegend=False),
    row=2, col=1
)

fig.add_trace(
    go.Scatter(x=X5[:,0], y=X5[:,1],
              mode='markers', marker=dict(color=list(map(SetColor, y5))),
              showlegend=False),
    row=2, col=2
)

fig.update_layout(title_text='ADASYN with K_neighbors')

fig.show()

In [105]:
fig = px.scatter(X1, x=X1[:,0], y=X1[:,1], color=y1)
fig.show()

In [176]:
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
from sklearn.feature_selection import SelectKBest, chi2, f_classif, mutual_info_classif
x, y=load_digits(return_X_y=True)
from sklearn.pipeline import make_pipeline
import numpy as np
import pandas as pd
import plotly.express as px

In [167]:
sb_chi=SelectKBest(score_func=chi2)
x_chi=sb_chi.fit_transform(x,y)
np.where(sb_chi.get_support()==1)

(array([20, 21, 26, 30, 33, 34, 42, 43, 54, 62], dtype=int64),)

In [168]:
sb_chi.scores_.argsort()

array([24, 16, 56,  8, 31, 48, 40, 47, 23, 11,  4, 49, 15, 55,  3, 59,  1,
       12, 57,  7, 51, 52, 60, 17, 14, 45, 22, 63, 18, 25, 37, 10, 50,  9,
       27, 53, 35, 29, 36, 38,  2, 19, 13, 28, 58, 41,  5,  6, 44, 61, 46,
       26, 21, 20, 62, 30, 54, 34, 43, 33, 42, 39, 32,  0], dtype=int64)

In [169]:
sb_f=SelectKBest(score_func=f_classif)
x_f=sb_f.fit_transform(x,y)
print(sb_f.get_support().sum())
np.where(sb_f.get_support()==1)

10


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning:

Features [ 0 32 39] are constant.

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning:

invalid value encountered in true_divide



(array([10, 20, 21, 26, 28, 33, 34, 36, 42, 43], dtype=int64),)

In [170]:
sb_chi.pvalues_.argsort()

array([63, 54, 28, 29, 30, 62, 58, 33, 34, 35, 36, 26, 37, 41, 42, 43, 44,
       45, 46, 50, 51, 52, 53, 38, 25, 27, 13, 61,  9, 10,  6, 14,  2,  5,
       17, 18, 19, 20, 21, 22, 60,  7, 57, 12,  1, 59,  3, 55, 15, 49,  4,
       11, 23, 47, 40, 48, 31,  8, 56, 16, 24, 39, 32,  0], dtype=int64)

In [171]:
sb_f.scores_

array([         nan,  39.77670877, 161.66962131,  68.01284271,
        37.085693  , 126.41541048,  74.26391138,  17.28204084,
         1.73328376,  93.87300085, 205.13348801,  38.86089592,
        51.62522088, 166.97247543,  37.41350206,  10.97417161,
         0.71100904,  55.32842977, 138.10227535, 138.68433936,
       202.43528942, 234.21960737,  50.24960622,  11.47100745,
         0.87782927, 103.80241354, 293.09983163, 146.07649117,
       236.7444881 , 127.5841692 , 189.18278073,   4.03517196,
                nan, 312.78489658, 254.37524393, 136.20370677,
       220.78357776, 110.63540569, 147.22496837,          nan,
         6.90281305, 123.36344683, 268.76998164, 222.53295915,
       159.07418303,  85.78384611, 169.33840921,  10.53627776,
         1.35922709,  12.19342228, 115.41402772,  83.87060144,
        88.50634019, 139.19382977, 162.49090456,  17.53002847,
         1.01703597,  35.49323239, 163.49692878,  68.70759521,
       200.35796882, 178.71033228, 106.03150882,  30.67

In [172]:
sb_f.pvalues_

array([            nan, 4.99834376e-065, 8.12770776e-224, 7.82141288e-108,
       1.03883191e-060, 4.56052872e-184, 9.92420373e-117, 1.15850944e-027,
       7.66052413e-002, 2.05288354e-143, 7.83904161e-268, 1.45690786e-063,
       1.55742413e-083, 1.84517602e-229, 3.07811154e-061, 8.70497727e-017,
       6.99296954e-001, 3.74265221e-089, 1.07023842e-197, 2.30628015e-198,
       3.06673207e-265, 9.82716944e-295, 1.99271799e-081, 1.21078798e-017,
       5.44408914e-001, 2.86340363e-156, 0.00000000e+000, 9.88396955e-207,
       5.52772524e-297, 1.88118614e-185, 2.99386945e-252, 3.92803876e-005,
                   nan, 0.00000000e+000, 2.42398810e-312, 1.62783926e-195,
       1.54479017e-282, 7.04478594e-165, 5.13771578e-208,             nan,
       7.90550276e-010, 1.98515145e-180, 0.00000000e+000, 3.79380886e-284,
       5.03935070e-221, 1.26953521e-132, 5.94324696e-232, 4.94516665e-016,
       2.01446674e-001, 6.86214509e-019, 8.65547190e-171, 5.00690155e-130,
       2.74648230e-136, 6

In [177]:
md1 = make_pipeline(SelectKBest(k=30), PCA(n_components=3))
x_new=md1.fit_transform(x,y)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:114: UserWarning:

Features [ 0 32 39] are constant.

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_selection\_univariate_selection.py:116: RuntimeWarning:

invalid value encountered in true_divide



In [160]:
sb_m=SelectKBest(score_func=mutual_info_classif)
x_m=sb_m.fit_transform(x,y)
print(sb_m.get_support().sum())
np.where(sb_m.get_support()==1)

10


(array([21, 26, 28, 30, 33, 34, 36, 42, 43, 61], dtype=int64),)

In [148]:
sb_m.scores_

array([0.03774123, 0.13301515, 0.36868289, 0.18445259, 0.16720021,
       0.266778  , 0.17766331, 0.01139732, 0.        , 0.25834064,
       0.36221844, 0.11876846, 0.20558126, 0.36157496, 0.1177423 ,
       0.02067297, 0.        , 0.19367429, 0.26058741, 0.26287242,
       0.38468233, 0.42965375, 0.2180194 , 0.01550207, 0.        ,
       0.24454738, 0.40579123, 0.29694911, 0.40178708, 0.27259013,
       0.42679005, 0.01579131, 0.        , 0.42419617, 0.44013762,
       0.29247606, 0.36395439, 0.24948616, 0.3255857 , 0.00248291,
       0.        , 0.255682  , 0.40589539, 0.39209417, 0.29158455,
       0.20572634, 0.32559535, 0.03342164, 0.03096252, 0.029746  ,
       0.26394321, 0.22682391, 0.18841024, 0.31469709, 0.36812317,
       0.07510218, 0.02309367, 0.06904449, 0.34334539, 0.17436528,
       0.27246138, 0.373423  , 0.31028495, 0.07332306])

In [150]:
sb_m.pvalues_